application:
  name: allhailqr-app
  project: allhailqr
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: allhailqr-db
routers:
  - name: main
    routes:
      - application_name: allhailqr-app
        paths:
          - /
