application:
  name: my-application
  project: my-project
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: my-db
routers:
  - name: main
    routes:
      - application_name: my-application
        paths:
          - /
